version: '3'

services:
  api:
    container_name: api
    hostname: api
    restart: always
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      TYPEORM_HOST: postgres
      MINIO_END_POINT: minio
    depends_on:
      - postgres
      - minio
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      PGPORT: 5432
      POSTGRES_DB: magic_gophers_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./.docker-compose/postgresql/data/:/var/lib/postgresql/data/
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: miniorootuser
      MINIO_ROOT_PASSWORD: miniorootpassword
    volumes:
      - ./.docker-compose/minio/data:/data
    command: server --console-address ":9001" /data/
